name: stars

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo stars
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            const plural = (count) => count !== 1 ? 's' : '';
            const verb = (count) => count === 1 ? 'is' : 'are';
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            const {
              data: {
                name,
                description,
                stargazers_count,
                watchers_count,
                forks_count,
                open_issues_count,
                network_count,
                subscribers_count,
              }
            } = await github.repos.get({
              owner,
              repo,
            });
            const adjustedName = `${stargazers_count}-star${plural(stargazers_count)}-${
              verb(stargazers_count)}-not-enough`;
            const adjustedDescription = `Efficient octokit action schedule demonstration. Give this repository more than ${
              stargazers_count} star${plural(stargazers_count)}, ${
              forks_count} fork${plural(forks_count)} and ${
              subscribers_count} subscriber${plural(subscribers_count)} and check it update 🚀`;
            if (name !== adjustedName || description !== adjustedDescription) {
              await github.repos.update({
                owner,
                repo,
                name: adjustedName,
                description: adjustedDescription,
              });
            }
            
            
