name: stars

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo stars
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            const plural = (count) => count !== 1 ? 's' : '';
            const verb = (count) => count === 1 ? 'is' : 'are';
            const {
              name,
              owner: {login},
              description,
              forks_count,
              stargazers_count,
              watchers_count,
            } = context.payload.repository;
            const adjustedName = `${stargazers_count}-star${plural(stargazers_count)}-${
              verb(stargazers_count)}-not-enough`;
            const adjustedDescription = `This repository seriously needs more than ${
              stargazers_count} star${plural(stargazers_count)}, ${
              forks_count} fork${plural(forks_count)} and ${
              watchers_count} stalker${plural(watchers_count)} 🚀`;
            if (name !== adjustedName || description !== adjustedDescription) {
              await github.repos.update({
                owner: login,
                repo: name,
                name: adjustedName,
                description: adjustedDescription,
              });
            }
